substitutions:
  _DIR: task-af/

steps:
  - id: 'rsync airflow jobs'
    name: 'gcr.io/cloud-builders/gsutil'
    dir: '${_APP}'
    entrypoint: bash
    args:
      - '-c'
      - |
        composerBucket=$(gcloud composer environments describe ${_COMPOSER_ENV_NAME} --location ${_COMPOSER_LOCATION} --format="get(config.dagGcsPrefix)")
        gsutil -m rsync -d -r -c -x "tests/.*|.*\.pyc$|README\.md|pyproject\.toml|poetry\.lock|Task 3.docx|" . ${composerBucket}/${_APP}/
tags: ['aspire-service-${_APP}-airflow']
