# substitutions:
#   _APP: 'cf-tasks/terraform'
#   _PY_DIR: 'cf-tasks/function'
#   _TF_DIR: 'cf-tasks/terraform'
#   _TF_ACTION: 'apply'

steps:
  # - id: "ls"
  #   name: 'ubuntu'
  #   args:
  #     - 'ls'
  
  # - id: "pwd"
  #   name: 'ubuntu'
  #   args:
  #     - 'pwd'

  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    dir: 'cf-tasks/terraform'
    args:
      - '-c'
      - 'terraform init'

  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    dir: 'cf-tasks/terraform'
    args:
      - '-c'
      - 'terraform plan -destroy -out=cf-tasks/terraform/plan.out'

  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    dir: 'cf-tasks/terraform'
    args:
      - '-c'
      - 'terraform apply cf-tasks/terraform/plan.out'
  
  # - id: 'tf destroy'
  #   name: 'hashicorp/terraform:1.0.0'
  #   entrypoint: sh
  #   args:
  #     - '-c'
  #     - 'terraform plan -destroy -out=plan.out'

  # - id: 'tf destroy plan'
  #   name: 'hashicorp/terraform:1.0.0'
  #   entrypoint: sh
  #   args:
  #     - '-c'
  #     - 'terraform apply plan.out'

# options:
#   logging: CLOUD_LOGGING_ONLY

# options:
#   substitution_option: 'ALLOW_LOOSE'
# tags: ['service-${_APP}-${_TF_ACTION}']
