substitutions:
  _APP: 'cf-tasks/terraform'
  _PY_DIR: 'cf-tasks/function'
  _TF_DIR: 'cf-tasks/terraform'
  _TF_ACTION: 'apply'

steps:
  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - 'terraform init -upgrade'

  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - 'terraform plan -lock=false -out=plan.out'

  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: sh
    args:
      - '-c'
      - 'terraform apply -lock=false plan.out'

# options:
#   logging: CLOUD_LOGGING_ONLY

options:
  substitution_option: 'ALLOW_LOOSE'
tags: ['service-${_APP}-${_TF_ACTION}']
